Minor fix in install scripts

diff --git a/frameworks/install_theme b/frameworks/install_theme
--- a/frameworks/install_theme
+++ b/frameworks/install_theme
@@ -1,2 +1,15 @@
 #!/bin/sh
-cp /opt/src/modifications/frameworks/kb_themes.tar / && cd / && tar -xvf kb_themes.tar && rm kb_themes.tar && cd -
+echo "Remounting / rw..."
+mount -o rw,remount /
+if [ $? -ne 0 ]
+then
+  echo "ERROR: Could not remount / in rw"
+  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
+  exit 1
+fi
+
+cp /opt/src/modifications/frameworks/kb_themes.tar / && cd / && tar -xvf kb_themes.tar && rm kb_themes.tar && cd - && echo "SUCCESS"
+
+echo "Remounting / to read-only"
+mount -o ro,remount /
+
