Fixed emulator to not try to remount /

diff --git a/frameworks/install_kb b/frameworks/install_kb
--- a/frameworks/install_kb
+++ b/frameworks/install_kb
@@ -5,6 +5,7 @@ PATCH=${PATCH_PRE}
 
 if [ "$1" = "emulator" ]
 then
+  EMULATOR=yes
   cd /opt/src/modifications/frameworks
   rm -f ${PATCH_EMU}
   git pull
@@ -22,17 +23,22 @@ then
   exit 1
 fi
 
-echo "Remounting / rw..."
-mount -o rw,remount /
-if [ $? -ne 0 ]
+if [ "$EMULATOR" = "" ]
 then
-  echo "ERROR: Could not remount / in rw"
-  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
-  exit 1
+  echo "Remounting / rw..."
+  mount -o rw,remount /
+  if [ $? -ne 0 ]
+  then
+    echo "ERROR: Could not remount / in rw"
+    echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
+    exit 1
+  fi
 fi
 
 cp /opt/src/modifications/frameworks/virtual-keyboard-themes.tar.gz / && cd / && tar -xvzf virtual-keyboard-themes.tar.gz && cd - && echo "SUCCESS"
 
-echo "Remounting / to read-only"
-mount -o ro,remount /
-
+if [ "$EMULATOR" = "" ]
+then
+  echo "Remounting / to read-only"
+  mount -o ro,remount /
+fi
diff --git a/install b/install
--- a/install
+++ b/install
@@ -71,13 +71,16 @@ then
 fi
 
 
-echo "Remounting / rw..."
-mount -o rw,remount /
-if [ $? -ne 0 ]
+if [ "$EMULATOR" = "" ]
 then
-  echo "ERROR: Could not remount / in rw"
-  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
-  exit 1
+  echo "Remounting / rw..."
+  mount -o rw,remount /
+  if [ $? -ne 0 ]
+  then
+    echo "ERROR: Could not remount / in rw"
+    echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
+    exit 1
+  fi
 fi
 
 echo "Popping all previous patches..."
@@ -106,5 +109,8 @@ fi
 
 echo "SUCCESS"
 
-echo "Remounting / to read-only"
-mount -o ro,remount /
+if [ "$EMULATOR" = "" ]
+then
+  echo "Remounting / to read-only"
+  mount -o ro,remount /
+fi
