Fixed to import after popping, not before!

diff --git a/install b/install
--- a/install
+++ b/install
@@ -78,19 +78,6 @@ then
 fi
 
 
-PATCH_PATH=`find ${GIT_PATH} -name ${PATCH_NAME}`
-echo "Importing patch ${PATCH_PATH}..."
-quilt import -f ${PATCH_PATH}
-
-echo "Verifying patch is in quilt series..."
-quilt series | grep $PATCH_NAME
-if [ $? -ne 0 ]
-then
-  echo "ERROR: Cannot find patch in series"
-  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
-  exit 1
-fi
-
 echo "Remounting / rw..."
 mount -o rw,remount /
 if [ $? -ne 0 ]
@@ -105,6 +92,19 @@ quilt pop -a
 if [ $? -ne 0 ]
 then
   echo "ERROR: Could not pop patch"
+  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
+  exit 1
+fi
+
+PATCH_PATH=`find ${GIT_PATH} -name ${PATCH_NAME}`
+echo "Importing patch ${PATCH_PATH}..."
+quilt import -f ${PATCH_PATH}
+
+echo "Verifying patch is in quilt series..."
+quilt series | grep $PATCH_NAME
+if [ $? -ne 0 ]
+then
+  echo "ERROR: Cannot find patch in series"
   echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
   exit 1
 fi
