Fixed bug that caused script to exit with error if no patches existed in quilt series.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -87,13 +87,18 @@ then
   exit 1
 fi
 
-echo "Popping previous patches..."
-quilt pop -a
-if [ $? -ne 0 ]
+echo "Checking for patches in series..."
+quilt series | grep patch
+if [ $? -eq 0 ]
 then
-  echo "ERROR: Could not pop patch"
-  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
-  exit 1
+  echo "Popping previous patches..."
+  quilt pop -a
+  if [ $? -ne 0 ]
+  then
+    echo "ERROR: Could not pop patch"
+    echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
+    exit 1
+  fi
 fi
 
 PATCH_PATH=`find ${GIT_PATH} -name ${PATCH_NAME}`
