Modified to always pop/push all patches

diff --git a/install b/install
--- a/install
+++ b/install
@@ -78,27 +78,17 @@ then
 fi
 
 
-if [ "$PATCH_NAME" = "" ]
-then
-  MAYBE_ALL=-a
-else
-  #echo "Checking for patch in quilt series..."
-  #quilt series | grep $PATCH_NAME
-  #if [ $? -ne 0 ]
-  #then
-    PATCH_PATH=`find ${GIT_PATH} -name ${PATCH_NAME}`
-    echo "Importing patch ${PATCH_PATH}..."
-    quilt import -f ${PATCH_PATH}
-  #fi
+PATCH_PATH=`find ${GIT_PATH} -name ${PATCH_NAME}`
+echo "Importing patch ${PATCH_PATH}..."
+quilt import -f ${PATCH_PATH}
 
-  echo "Verifying patch is in quilt series..."
-  quilt series | grep $PATCH_NAME
-  if [ $? -ne 0 ]
-  then
-    echo "ERROR: Cannot find patch in series"
-    echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
-    exit 1
-  fi
+echo "Verifying patch is in quilt series..."
+quilt series | grep $PATCH_NAME
+if [ $? -ne 0 ]
+then
+  echo "ERROR: Cannot find patch in series"
+  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
+  exit 1
 fi
 
 echo "Remounting / rw..."
@@ -110,8 +100,8 @@ then
   exit 1
 fi
 
-echo "Popping previous patch..."
-quilt pop $MAYBE_ALL
+echo "Popping previous patches..."
+quilt pop -a
 if [ $? -ne 0 ]
 then
   echo "ERROR: Could not pop patch"
@@ -119,8 +109,8 @@ then
   exit 1
 fi
 
-echo "Pushing new patch..."
-quilt push $MAYBE_ALL
+echo "Pushing new patches..."
+quilt push -a
 if [ $? -ne 0 ]
 then
   echo "ERROR: Could not push patch"
